"""create recipes and ingredients tables

Revision ID: fb8cdb59d447
Revises: 714a36c24d93
Create Date: 2026-05-13 10:01:09.496081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fb8cdb59d447"
down_revision: Union[str, Sequence[str], None] = "714a36c24d93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recipies_name"), table_name="recipies", if_exists=True)
    op.drop_table("recipies", if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipies",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("source_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "labels", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("recipies_pkey")),
    )
    op.create_index(op.f("ix_recipies_name"), "recipies", ["name"], unique=False)
    # ### end Alembic commands ###
